import ReuseAble from "@/component/ReuseAble";
import Head from "next/head";
import { Avi, Avi2, Avi3, Banner, BannerMobile } from "../../public/assets";
import { Firstline, ProfileAdd, Avalanche } from "iconsax-react";
import BannerImage from "@/component/BannerImage";
import Faq from "@/component/Faq";
export default function Home() {
  return (
    <>
      <Head>
        <title>Demo Next Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="pb-16">
        <div className="name">
          <ReuseAble
            title="services"
            header1="Co-Nodes® "
            header2="Managed nodes"
            header3="Nodes as a service"
            text1="Collaborative staking among users to pool to achieve threshold stake and operate collectively. This democratises participation and allows sub-stake holders to benefit from reward protocols. It also enables compounding as participants can sweep earned rewards into further Co-Nodes"
            text2="Outsource node deployment, management, and maintenance to Node Army for a small commission of earned rewards. Develop a passive yield portfolio with minimum time and skill commitment."
            text3="An industrial node solution for projects requiring robust decentralised node infrastructures at scale. Node Army collaborates with projects during development phase and through a blockchain lifecycle."
            img={Avi}
            icon={<ProfileAdd />}
          />
          <ReuseAble
          header1="Rewards"
          header2="Node build templates"
          header3="Blockchain scalability "
          text1="Participate in underlying projects offering rewards for staking, validating, and securing their network through a transparent process. Node Army does not offer or promote its own Node Army yield, but rewards are transparently distributed on the blockchain according to the underlying project's protocol and tokenomics.
          "
          text2="Easily deploy nodes with pre-built templates hosted in the Marketplaces of premier cloud computing providers. Templates are specific to the different underlying blockchain networks, designed to make deployment seamless."
          text3="Leverage scalable blockchain infrastructure and a substantial and growing community of committed datapreneurs for rapid and effective scaling of blockchain-based applications. Maintain high performance and security in a decentralised approach.
          "
          img={Avi2}
          icon={<Firstline />}
          mediacol
        />
         <br />

<BannerImage img={Banner}  />
<BannerImage img={BannerMobile} ismobile />

        <ReuseAble
          title="Environment statement"
          header1="proof of stake"
          header2="Cloud computing"
          header3="Node army "
          text1="Proof of stake blockchain validation is more environmentally friendly than proof of work, as it consumes significantly less energy by not requiring computational puzzles to be solved. Validators are selected based on cryptocurrency holdings, reducing the carbon footprint of the network.
          Unless directly disclosed none of the projects we support will operate through Proof of Work.
          "
          text2="Cloud computing provides more efficient resource usage , reducing the need for physical hardware and lowering the carbon footprint of the network. Other benefits include increased scalability, faster transaction speeds, and improved accessibility. 
          Overall, cloud computing provides an eco-friendly and efficient solution for validating and recording transactions on PoS blockchains."
          text3="We regularly review cloud computing platforms to ensure you can choose from proven, reliable, scalable and environmentally responsible providers. Node Army will endeavor to integrate a energy utilization metric to our and your dashboards in the near future for transparency of impact
          "
          img={Avi3}
          icon={<Avalanche />}
          mediacol
        />
        <Faq />
        </div>
      </main>
    </>
  );
}
